// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class AuditDetail
    {
        public AuditDetail()
        {
            AuditDetailSerial = new HashSet<AuditDetailSerial>();
        }

        public string Id { get; set; }
        public string AuditId { get; set; }
        public string ItemId { get; set; }
        public decimal Quantity { get; set; }
        public decimal AuditQuantity { get; set; }
        public string Conclude { get; set; }
        public bool OnDelete { get; set; }

        public virtual Audit Audit { get; set; }
        public virtual WareHouseItem Item { get; set; }
        public virtual ICollection<AuditDetailSerial> AuditDetailSerial { get; set; }
    }
}