// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class Audit
    {
        public Audit()
        {
            AuditCouncil = new HashSet<AuditCouncil>();
            AuditDetail = new HashSet<AuditDetail>();
        }

        public string Id { get; set; }
        public string VoucherCode { get; set; }
        public DateTime VoucherDate { get; set; }
        public string WareHouseId { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool OnDelete { get; set; }

        public virtual WareHouse WareHouse { get; set; }
        public virtual ICollection<AuditCouncil> AuditCouncil { get; set; }
        public virtual ICollection<AuditDetail> AuditDetail { get; set; }
    }
}