// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class AuditDetailSerial
    {
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string Serial { get; set; }
        public string AuditDetailId { get; set; }
        public bool OnDelete { get; set; }

        public virtual AuditDetail AuditDetail { get; set; }
        public virtual WareHouseItem Item { get; set; }
    }
}