// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class SerialWareHouse
    {
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string Serial { get; set; }
        public string InwardDetailId { get; set; }
        public string OutwardDetailId { get; set; }
        public bool IsOver { get; set; }
        public bool OnDelete { get; set; }

        public virtual InwardDetail InwardDetail { get; set; }
        public virtual WareHouseItem Item { get; set; }
        public virtual OutwardDetail OutwardDetail { get; set; }
    }
}