// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class Unit
    {
        public Unit()
        {
            BeginningWareHouse = new HashSet<BeginningWareHouse>();
            InwardDetail = new HashSet<InwardDetail>();
            OutwardDetail = new HashSet<OutwardDetail>();
            WareHouseItem = new HashSet<WareHouseItem>();
            WareHouseItemUnit = new HashSet<WareHouseItemUnit>();
            WareHouseLimit = new HashSet<WareHouseLimit>();
        }

        public string Id { get; set; }
        public string UnitName { get; set; }
        public bool Inactive { get; set; }
        public bool OnDelete { get; set; }

        public virtual ICollection<BeginningWareHouse> BeginningWareHouse { get; set; }
        public virtual ICollection<InwardDetail> InwardDetail { get; set; }
        public virtual ICollection<OutwardDetail> OutwardDetail { get; set; }
        public virtual ICollection<WareHouseItem> WareHouseItem { get; set; }
        public virtual ICollection<WareHouseItemUnit> WareHouseItemUnit { get; set; }
        public virtual ICollection<WareHouseLimit> WareHouseLimit { get; set; }
    }
}