// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class Vendor
    {
        public Vendor()
        {
            Inward = new HashSet<Inward>();
            WareHouseItem = new HashSet<WareHouseItem>();
        }

        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public bool Inactive { get; set; }
        public bool OnDelete { get; set; }

        public virtual ICollection<Inward> Inward { get; set; }
        public virtual ICollection<WareHouseItem> WareHouseItem { get; set; }
    }
}