// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class WareHouseItemUnit
    {
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string UnitId { get; set; }
        public int ConvertRate { get; set; }
        public bool? IsPrimary { get; set; }
        public bool OnDelete { get; set; }

        public virtual WareHouseItem Item { get; set; }
        public virtual Unit Unit { get; set; }
    }
}