// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class WareHouseItemCategory
    {
        public WareHouseItemCategory()
        {
            InverseParent = new HashSet<WareHouseItemCategory>();
            WareHouseItem = new HashSet<WareHouseItem>();
        }

        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public bool? Inactive { get; set; }
        public bool OnDelete { get; set; }

        public virtual WareHouseItemCategory Parent { get; set; }
        public virtual ICollection<WareHouseItemCategory> InverseParent { get; set; }
        public virtual ICollection<WareHouseItem> WareHouseItem { get; set; }
    }
}