// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class WareHouseItem
    {
        public WareHouseItem()
        {
            AuditDetail = new HashSet<AuditDetail>();
            AuditDetailSerial = new HashSet<AuditDetailSerial>();
            BeginningWareHouse = new HashSet<BeginningWareHouse>();
            InwardDetail = new HashSet<InwardDetail>();
            OutwardDetail = new HashSet<OutwardDetail>();
            SerialWareHouse = new HashSet<SerialWareHouse>();
            WareHouseItemUnit = new HashSet<WareHouseItemUnit>();
            WareHouseLimit = new HashSet<WareHouseLimit>();
        }

        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string CategoryId { get; set; }
        public string Description { get; set; }
        public string VendorId { get; set; }
        public string VendorName { get; set; }
        public string Country { get; set; }
        public string UnitId { get; set; }
        public bool? Inactive { get; set; }
        public bool OnDelete { get; set; }

        public virtual WareHouseItemCategory Category { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<AuditDetail> AuditDetail { get; set; }
        public virtual ICollection<AuditDetailSerial> AuditDetailSerial { get; set; }
        public virtual ICollection<BeginningWareHouse> BeginningWareHouse { get; set; }
        public virtual ICollection<InwardDetail> InwardDetail { get; set; }
        public virtual ICollection<OutwardDetail> OutwardDetail { get; set; }
        public virtual ICollection<SerialWareHouse> SerialWareHouse { get; set; }
        public virtual ICollection<WareHouseItemUnit> WareHouseItemUnit { get; set; }
        public virtual ICollection<WareHouseLimit> WareHouseLimit { get; set; }
    }
}