// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseHA.Domain.Entity
{
    public partial class WareHouse
    {
        public WareHouse()
        {
            Audit = new HashSet<Audit>();
            BeginningWareHouse = new HashSet<BeginningWareHouse>();
            Inward = new HashSet<Inward>();
            OutwardToWareHouse = new HashSet<Outward>();
            OutwardWareHouse = new HashSet<Outward>();
            WareHouseLimit = new HashSet<WareHouseLimit>();
        }

        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string ParentId { get; set; }
        public string Path { get; set; }
        public bool Inactive { get; set; }
        public bool OnDelete { get; set; }

        public virtual ICollection<Audit> Audit { get; set; }
        public virtual ICollection<BeginningWareHouse> BeginningWareHouse { get; set; }
        public virtual ICollection<Inward> Inward { get; set; }
        public virtual ICollection<Outward> OutwardToWareHouse { get; set; }
        public virtual ICollection<Outward> OutwardWareHouse { get; set; }
        public virtual ICollection<WareHouseLimit> WareHouseLimit { get; set; }
    }
}